#%RAML 1.0
title: mrll-q2c-project-dev
version: 1.0
baseUri: http://127.0.0.1/api/{version}
protocols: HTTP
mediaType: application/json

/project/testing:
  get:
    responses:
      200:
      400:
      500:
/newproject/testing:
  get:
    responses:
      200:
      400:
      500: